name: Flutter Build IPA

on:
  push:
    branches:
      - main  # 触发分支
  workflow_dispatch:  # 手动触发

jobs:
  build:
    name: Build iOS IPA
    runs-on: macos-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 'stable'  # 指定 Flutter 版本

      - name: Install dependencies
        run: flutter pub get

      - name: Build iOS app
        run: flutter build ios --release --no-codesign

      - name: Create IPA
        run: |
          cd build/ios/iphoneos
          mkdir Payload
          mv Runner.app Payload/
          zip -r Runner.ipa Payload
          mv Runner.ipa ../../../../

      - name: Upload IPA
        uses: actions/upload-artifact@v3
        with:
          name: Runner.ipa
          path: Runner.ipa
